### ISSUE TITLE
v2.8.0 Milestone

### ISSUE THREAD

**Issue by AigioL** [BeyondDimension/SteamTools#1669]
## 测试清单
- 新增 Steam 云存档管理功能，可自行上传或删除 Steam 云存档
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS (不支持筛选当前账户下的游戏 可能造成开启没反应)
    - [x] arm64
    - [x] x64
  - [x] Linux (不支持筛选当前账户下的游戏 可能造成开启没反应)
- 库存游戏支持筛选支持 Steam 云存档的游戏
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] x64
    - [x] arm64
  - [x] Linux
- ASF 升级至
  - [x] V5.2.7.7
    - [x] Windows
      - [x] x64
      - [x] x86
    - [x] macOS
      - [x] arm64
      - [x] x64
    - [x] Linux
    - [ ] Android
  - [x] ~~V5.2.6.3~~
- 库存游戏中解锁成就与挂时长支持 macOS 与 Linux 系统
  - [x] macOS
  - [x] Linux
- 在设置中可关闭托盘，关闭托盘后关闭主窗口即退出程序
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 使用 Yarp.ReverseProxy 重写了反代加速和脚本功能，大幅提升稳定性和性能
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- Windows 新增 DNS 驱动拦截模式进行本地加速
  - [x] Windows
    - [x] x64
    - [x] x86
- 广告
  - [ ] 招商中…
- 修复 Windows 系统下窗口在某些情况下最大化或最小化恢复时窗口大小会变化的问题 
  - [x] Windows
    - [x] x64
    - [x] x86
- 修复 库存游戏 编辑 Steam 游戏封面时选择自定义图片失败的问题
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 修复 程序内在显示某些图片时会出现错乱马赛克的问题
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 修复 Linux 上点击关于页面可能因字体引发闪退
  - [x] Linux
- 修复 MIUI Android 11 ~ 12 中绑定或换绑手机号页面闪退
  - [x] Android
- 修复 Android 本地加速中已知问题弹窗显示时不应同时跳转引导证书页
  - [x] Android
- UI 主题切换
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 令牌交易详情(WebView)
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS (没弹出网页浏览器)
    - [x] arm64
    - [x] x64
  - [x] Linux (没弹出网页浏览器)
  - [ ] Android
- 每个平台的广告显示隐藏效果
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 服务端控制广告显示隐藏效果
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 用户签到
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 覆盖更新后测试加速是否会要重新生成证书
  - [ ] Windows
    - [ ] x64
    - [ ] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 旧的加速配置文件读取是否正常
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 非简中语言界面是否正常
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS [Korean字体重叠]
    - [x] arm64
    - [x] x64
  - [x] Linux [Korean字体重叠]
  - [ ] Android
- 库存游戏编辑功能每个平台读取存档路径是否正常（多测试些游戏）
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux 目前闪退 = 
- 关闭托盘后关闭程序是否正常直接退出
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS
    - [x] arm64
    - [x] x64
  - [x] Linux
- 第三方快速登录(Steam渠道)
  - [x] Windows
    - [x] x64
    - [x] x86
  - [x] macOS (目前WS 高版本失效只能手动复制登录)
    - [x] arm64
    - [x] x64
  - [x] Linux
  - [ ] Android
- 第三方快速登录(QQ渠道)
  - [ ] Windows
    - [x] x64
    - [ ] x86
  - [x] macOS (目前WS 高版本失效只能手动复制登录)
    - [x] arm64
    - [x] x64
  - [x] Linux
  - [ ] Android
- 第三方快速登录(MS渠道)
  - [x] Windows
    - [x] x64
    - [ ] x86
  - [x] macOS (目前WS 高版本失效只能手动复制登录)
    - [x] arm64
    - [x] x64
  - [x] Linux
  - [ ] Android
- Android 检查更新提示新版本(因流量经济问题暂不开放直接下载apk包，点击更新跳转官网)
  - [ ] Android
- Windows 32 位(x86)打包
  - [x] Windows
- Windows 低版本兼容性测试
  - [x] Windows 7
  - [x] Windows 8.1

## New release previous preparations | 发行新版本前准备工作
- [x] Translate resx | 翻译 resx
- [ ] Compile msixupload  package | 编译 msixupload 包
- [ ] Github release / Gitee release | 在 Github 与 Gitee 上发布
- [ ] Upload network disk | 上传网盘
- [x] Update the official website | 更新官网 (已添加Json 等待补充更新日志)
- [ ] Server publishing tool enable new version | 服务器发布工具启用新版本
- [ ] ~~Enable MS store channel new version notification after waiting for MS store approval | 等待微软商店审核完成后启用该渠道新版本通知~~

**Comment by shiquda** [comment]
大概什么时候会发布2.8？😄

**Comment by AigioL** [comment]
> 大概什么时候会发布2.8？😄

最近几天
