### ISSUE TITLE
v3.0 Milestone

### ISSUE THREAD

**Issue by AigioL** [BeyondDimension/SteamTools#2339]
## 任务
- [x] .NET 7 ```⚠️这是一个新的主要版本。从显着的变化来看，这个版本为平台带来了许多性能改进。在兼容性方面，不再支持达到 EOL 的操作系统，尤其是 Windows 7 和 8.1。```
  - [x] net7.0-macos
  - [x] net7.0-maccatalyst
  - [x] Server
    - [x] RESTful API
- [x] Avalonia 11
- [x] 重构
  - [x] Client
    - [x] UI(XAML)
      - [x] Responsive(Desktop/Mobile) UI
      - [ ] ~~WebAssembly WebUI~~
    - [x] Code(C#)
      - [x] [Source Generators](https://learn.microsoft.com/zh-cn/dotnet/csharp/roslyn-sdk/source-generators-overview)
        - [x] [GeneratedRegex](https://learn.microsoft.com/zh-CN/dotnet/standard/base-types/regular-expression-source-generators)
      - [x] [UTF-8 string literals](https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/reference-types#utf-8-string-literals) ```ReadOnlySpan<byte> span = "hello"u8;```
      - [x] [MemoryPack](https://github.com/Cysharp/MemoryPack)
  - [x] Server
  - [x] 更多单元测试
- [ ] ~Windows Arm64~ steamclient.dll 缺少 Arm64，以及 Arm64EC 在 dotnet 中目前不可用
- [x] 针对 Steam Deck ™ 优化
- [ ] ~~Android App~~
- [ ] ~~iOS/iPad App~~
- [ ] ~~Native AOT~~
- [x] 需要修复的问题
  - [x] 签到不重启程序第二天无法成功签到
  - [x] 非管理员权限带参数启动 Steam 失败
  - [x] 更佳的检测 IPV6 方法
  - [x] 当前版本存在潜在的内存溢出问题，怀疑是 SkiaSharp 或 图表控件导致的，希望升级到 Avalonia 11 后相关依赖库更新能解决
- [ ] ~~使用 ```Environment.UserInteractive``` 区分是否加载 UI，并支持命令行模式~~
  - [ ] 命令行模式 Docker 支持
- [x] 插件化
- [x] 子进程管理与 IPC 调用
  - [x] 命名管道全双工通信，多线程
  - [x] 管理员或 Root 权限使用子进程执行，主进程不在要求管理员权限，管理员权限运行的只执行预设的一些命令与逻辑，避免插件加载在高权限上运行
- [x] 由于 AspNetCore 目前不支持 tfm 原 xamarin 部分，拆分成独立子进程
- [x] 加速子进程模块，标准 AspNetCore 项目
  - [ ] ~~支持 Docker 发布，可运行在 OpenWrt 上~~
    - [ ] #2306
    - [ ] #2263
    - [ ] #123
    - [ ] OpenWrt 插件
    - [ ] Asuswrt Merlin 插件
  - [ ] ~~使用 .NET 8 AOT 编译更小的体积，更小的内存占用，以便运行在配置较低的设备上，如 华硕 RT-AC68U~~
- [ ] ~~匿名统计允许关闭，用户体验改进计划收集可选数据文案~~
- [ ] ~~Implementation DnsDohAnalysisService #2662~~ 暂缓
- [x] 全新的 UI 设计
- [ ] ~~网络加速与脚本管理 本地化多语言支持~~
  - [ ] 对于非简体中文语言添加提示，在其他地区可能加速效果不佳甚至减速，可不勾选加速项目，仅使用脚本功能
- [x] 新的设置配置文件使用 json，应在离开设置页面或失去焦点时保存文件，不应在退出程序时保存文件 #2682
  - [x] 当前版本中存在配置文件可能在保存时出现问题导致数据没有正确写入文件
  - [x] 对文件的监控以用于热重载
  - [x] 对文件读取失败的情况下尝试一些容错机制
  - [x] 每次保存配置对上一次配置进行备份？在当前配置文件出现问题时载入备份？
  - [ ] ~~从旧的配置格式上读取~~

## New release previous preparations | 发行新版本前准备工作
- [ ] Translate resx | 翻译 resx
- [ ] Compile msixupload  package | 编译 msixupload 包
- [ ] Github release / Gitee release | 在 Github 与 Gitee 上发布
- [ ] Upload network disk | 上传网盘
- [ ] Update the official website | 更新官网
- [ ] Server publishing tool enable new version | 服务器发布工具启用新版本
- [ ] ~~Enable MS store channel new version notification after waiting for MS store approval | 等待微软商店审核完成后启用该渠道新版本通知~~

**Comment by JerryFrancisco** [comment]
3.0版本什么时候上线呢

**Comment by AigioL** [comment]
> 3.0版本什么时候上线呢

快了

**Comment by Bpc-CPU** [comment]
watt toolkit的openwrt插件是不是可以不用跑在docker上面吧？
