### ISSUE TITLE
vTBD Milestone

### ISSUE THREAD

**Issue by usuarrio-id81214293** [BeyondDimension/SteamTools#3508]
## New release previous preparations | 发行新版本前准备工作
- [x] Translate resx | 翻译 resx
- [x] Compile msixupload  package | 编译 msixupload 包
- [x] Github release / Gitee release | 在 Github 与 Gitee 上发布
- [x] Upload network disk | 上传网盘
- [x] Update the official website | 更新官网
- [x] Server publishing tool enable new version | 服务器发布工具启用新版本
- [x] ~~Enable MS store channel new version notification after waiting for MS store approval | 等待微软商店审核完成后启用该渠道新版本通知~~

**Comment by Mossimos** [comment]
不要乱玩
