### ISSUE TITLE
v2.6.5 Milestone

### ISSUE THREAD

**Issue by AigioL** [BeyondDimension/SteamTools#871]
- [x] Windows
    - [x] 改进 打开 Web 链接失败时，通常为未设置系统默认浏览器的错误提示 ```Process2.OpenCoreByProcess```
    - [x] 改进 JumpList 在 Windows 10.0.10586 上使用 UWP API
        - [x] [Windows.UI.StartScreen.JumpList](https://docs.microsoft.com/zh-cn/uwp/api/Windows.UI.StartScreen.JumpList)
    - [x] 安装包默认路径改为 $PROGRAMFILES64
        - #271
        - #861
        - 读取 32 位注册表 HKEY_LOCAL_MACHINE\SOFTWARE\Steam++\InstPath 比对路径判断是否为安装版
        - AppData 目录移至 %LocalAppData%\Steam++
        - Cache 目录移至 %Tmp%\Steam++
        - 日志文件夹全部移动到 Cache 目录中
        - 安装版卸载时默认勾选删除数据将删除 AppData 与 Cache 目录
    - [x] #889
- [ ] Server
    - [x] JWT 允许多平台设备登录
        - [x] Deploy
    - [x] VersionController.CheckUpdate3，取消参数 isRunningAsUwp，从 Referer 中判断
        - [x] GetAppVerAsync(this ControllerBase controller)
        - [x] GetAppVerAsync(this HttpContext context)
        - [x] GetOSName(this HttpRequest request)
        - [x] GetOSName(this HttpContext context)
        - [x] GetOSName(this ControllerBase controller)
- [ ] Android
    - [x] 包含全部 ABI 的单一 APK 包代替之前的每个 ABI 单独 APK 包
    - [x] ASP.NET Core Update v2.2.5
    - [x] Android 12 / TargetSdkVersion 31
        - [x] [Xamarin.Android 12.1 Release Notes](https://docs.microsoft.com/zh-cn/xamarin/android/release-notes/12/12.1)
        - [x] [行为变更：所有应用](https://developer.android.google.cn/about/versions/12/behavior-changes-all)
        - [x] [行为变更：以 Android 12 为目标平台的应用](https://developer.android.google.cn/about/versions/12/behavior-changes-12)
        - [x] [废弃](https://developer.android.google.cn/about/versions/12/deprecations)
    - [ ] [将现有的启动画面实现迁移到 Android 12 及更高版本](https://developer.android.google.cn/guide/topics/ui/splash-screen/migrate)
    - [ ] 账号功能
        - [x] LoginOrRegisterActivity
        - [x] UserBasicInfoFragment
        - [x] UserAccountBindFragment
        - [ ] BindPhoneNumberActivity
        - [ ] ChangePhoneNumberActivity
    - [ ] ~~脚本配置~~
    - [ ] 关于中的捐助与 UID 复制
    - [x] 本地加速
        - [x] 二级列表
        - [x] #923
- [ ] ASF
    - [x] Update v5.2.1.5-library
        - [ ] Test
    - [x] #890
    - [x] Android 
        - [x] 前台服务
        - [x] ExplorerActivity
        - [ ] ASF 配置
        - [ ] ~~Bot 配置~~
- [x] Desktop
    - [x] CommandBarButton 重置 Hosts 文件 & 打开 Hosts 所在文件夹
    - [x] 改进 Hosts 文件存在多个 Mark 导致操作失败的错误提示
- [x] Linux
    - [x] #909  
    - [x] #891 
        - System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.X11.X11Window.SetTransparencyLevelHint(WindowTransparencyLevel transparencyLevel) in /_/src/Avalonia.X11/X11Window.cs:line 1160

## New release previous preparations | 发行新版本前准备工作
- [ ] Translate resx | 翻译 resx
- [ ] Compile msixupload  package | 编译 msixupload 包
- [ ] Github release / Gitee release | 在 Github 与 Gitee 上发布
- [ ] Upload network disk | 上传网盘
- [ ] Update the official website | 更新官网
- [ ] Server publishing tool enable new version | 服务器发布工具启用新版本
- [ ] ~~Enable MS store channel new version notification after waiting for MS store approval | 等待微软商店审核完成后启用该渠道新版本通知~~

**Comment by tasty0tomato** [comment]
May I ask the version about ASP.NET Core? It seems that v2.2.5 is kind of old or it is the package from Xamarin.Android?

**Comment by AigioL** [comment]
> May I ask the version about ASP.NET Core? It seems that v2.2.5 is kind of old or it is the package from Xamarin.Android?

It's really old, but I can't use the new one because ASP Net core 3 only supports Net Core， Xamarin.Android uses mono, which is similar to Net framework, so in net6.0-android rtm Before, only the old version can be used.

The package uses nuget net standard library package

https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-6.0#aspnet-core-30-only-runs-on-net-core-30
https://github.com/BeyondDimension/ArchiSteamFarm/blob/v5.2.2.4-library/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj#L81
https://github.com/BeyondDimension/ArchiSteamFarm/blob/v5.2.2.4-library/Directory.Packages.props#L38
